// Command Cloudsmith-cli is a CLI + REPL for the Cloudsmith SDK,
// built on the AQL engine. Positional arguments are joined into a
// single AQL expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	"github.com/aql-lang/aql/eng/go/parser"
	sdk "github.com/voxgig-sdk/cloudsmith-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "cloudsmith"

// entitiesHelp is the space-separated entity list shown by :help.
const entitiesHelp = "abort alpine audit_log basic cargo cocoapod complete composer conan conda copy cran dart deb deny_policy dependency disable distribution_full distro docker dynamic_mapping ecdsa enable entitlement evaluation file format geoip gon gon2 gon3 gon4 gon5 gon6 gon7 gon8 gon9 gpg group helm hex history huggingface info invite license_policy limit luarock maven member move namespace namespace_audit_log npm nuget openid_connect org organization_group_sync organization_group_sync_status organization_invite organization_invite_extend organization_membership organization_membership_role_update organization_membership_visibility_update organization_package_license_policy organization_package_vulnerability_policy organization_saml_auth organization_team organization_team_member oss p2n p2n2 package package_deny_policy package_file_parts_upload package_file_upload package_license_policy_evaluation package_version_badge package_vulnerability_policy_evaluation privilege profile provider_setting provider_settings_write python quarantine quota raw refresh regenerate repo repository_audit_log repository_ecdsa_key repository_geo_ip_rule repository_geo_ip_status repository_geo_ip_test_address repository_gpg_key repository_privilege_input repository_retention_rule repository_rsa_key repository_token repository_token_refresh repository_token_sync repository_webhook repository_x509_ecdsa_certificate repository_x509_rsa_certificate reset resources_rate_check resync retention rpm rsa ruby saml_group_sync scan self service status status_basic storage_region swift sync tag team terraform test token transfer_region user user_auth_token user_authentication_token user_brief user_profile vagrant validate version vulnerability vulnerability_policy webhook x509_ecdsa x509_rsa"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	// Configure from the environment: CLOUDSMITH_APIKEY carries the API key and
	// CLOUDSMITH_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("CLOUDSMITH_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("CLOUDSMITH_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewCloudsmithSDK(opts)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case ":quit", ":q", ":exit":
			return
		case ":help", ":h", ":?":
			fmt.Fprintln(out, "commands: list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     :quit :help")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
