// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	sdk "github.com/voxgig-sdk/cloudsmith-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.CloudsmithSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.CloudsmithSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.CloudsmithSDK, name string) (sdk.CloudsmithEntity, error) {
	switch strings.ToLower(name) {
	case "abort":
		return client.Abort(nil), nil
	case "alpine":
		return client.Alpine(nil), nil
	case "audit_log":
		return client.AuditLog(nil), nil
	case "basic":
		return client.Basic(nil), nil
	case "cargo":
		return client.Cargo(nil), nil
	case "cocoapod":
		return client.Cocoapod(nil), nil
	case "complete":
		return client.Complete(nil), nil
	case "composer":
		return client.Composer(nil), nil
	case "conan":
		return client.Conan(nil), nil
	case "conda":
		return client.Conda(nil), nil
	case "copy":
		return client.Copy(nil), nil
	case "cran":
		return client.Cran(nil), nil
	case "dart":
		return client.Dart(nil), nil
	case "deb":
		return client.Deb(nil), nil
	case "deny_policy":
		return client.DenyPolicy(nil), nil
	case "dependency":
		return client.Dependency(nil), nil
	case "disable":
		return client.Disable(nil), nil
	case "distribution_full":
		return client.DistributionFull(nil), nil
	case "distro":
		return client.Distro(nil), nil
	case "docker":
		return client.Docker(nil), nil
	case "dynamic_mapping":
		return client.DynamicMapping(nil), nil
	case "ecdsa":
		return client.Ecdsa(nil), nil
	case "enable":
		return client.Enable(nil), nil
	case "entitlement":
		return client.Entitlement(nil), nil
	case "evaluation":
		return client.Evaluation(nil), nil
	case "file":
		return client.File(nil), nil
	case "format":
		return client.Format(nil), nil
	case "geoip":
		return client.Geoip(nil), nil
	case "gon":
		return client.Gon(nil), nil
	case "gon2":
		return client.Gon2(nil), nil
	case "gon3":
		return client.Gon3(nil), nil
	case "gon4":
		return client.Gon4(nil), nil
	case "gon5":
		return client.Gon5(nil), nil
	case "gon6":
		return client.Gon6(nil), nil
	case "gon7":
		return client.Gon7(nil), nil
	case "gon8":
		return client.Gon8(nil), nil
	case "gon9":
		return client.Gon9(nil), nil
	case "gpg":
		return client.Gpg(nil), nil
	case "group":
		return client.Group(nil), nil
	case "helm":
		return client.Helm(nil), nil
	case "hex":
		return client.Hex(nil), nil
	case "history":
		return client.History(nil), nil
	case "huggingface":
		return client.Huggingface(nil), nil
	case "info":
		return client.Info(nil), nil
	case "invite":
		return client.Invite(nil), nil
	case "license_policy":
		return client.LicensePolicy(nil), nil
	case "limit":
		return client.Limit(nil), nil
	case "luarock":
		return client.Luarock(nil), nil
	case "maven":
		return client.Maven(nil), nil
	case "member":
		return client.Member(nil), nil
	case "move":
		return client.Move(nil), nil
	case "namespace":
		return client.Namespace(nil), nil
	case "namespace_audit_log":
		return client.NamespaceAuditLog(nil), nil
	case "npm":
		return client.Npm(nil), nil
	case "nuget":
		return client.Nuget(nil), nil
	case "openid_connect":
		return client.OpenidConnect(nil), nil
	case "org":
		return client.Org(nil), nil
	case "organization_group_sync":
		return client.OrganizationGroupSync(nil), nil
	case "organization_group_sync_status":
		return client.OrganizationGroupSyncStatus(nil), nil
	case "organization_invite":
		return client.OrganizationInvite(nil), nil
	case "organization_invite_extend":
		return client.OrganizationInviteExtend(nil), nil
	case "organization_membership":
		return client.OrganizationMembership(nil), nil
	case "organization_membership_role_update":
		return client.OrganizationMembershipRoleUpdate(nil), nil
	case "organization_membership_visibility_update":
		return client.OrganizationMembershipVisibilityUpdate(nil), nil
	case "organization_package_license_policy":
		return client.OrganizationPackageLicensePolicy(nil), nil
	case "organization_package_vulnerability_policy":
		return client.OrganizationPackageVulnerabilityPolicy(nil), nil
	case "organization_saml_auth":
		return client.OrganizationSamlAuth(nil), nil
	case "organization_team":
		return client.OrganizationTeam(nil), nil
	case "organization_team_member":
		return client.OrganizationTeamMember(nil), nil
	case "oss":
		return client.Oss(nil), nil
	case "p2n":
		return client.P2n(nil), nil
	case "p2n2":
		return client.P2n2(nil), nil
	case "package":
		return client.Package(nil), nil
	case "package_deny_policy":
		return client.PackageDenyPolicy(nil), nil
	case "package_file_parts_upload":
		return client.PackageFilePartsUpload(nil), nil
	case "package_file_upload":
		return client.PackageFileUpload(nil), nil
	case "package_license_policy_evaluation":
		return client.PackageLicensePolicyEvaluation(nil), nil
	case "package_version_badge":
		return client.PackageVersionBadge(nil), nil
	case "package_vulnerability_policy_evaluation":
		return client.PackageVulnerabilityPolicyEvaluation(nil), nil
	case "privilege":
		return client.Privilege(nil), nil
	case "profile":
		return client.Profile(nil), nil
	case "provider_setting":
		return client.ProviderSetting(nil), nil
	case "provider_settings_write":
		return client.ProviderSettingsWrite(nil), nil
	case "python":
		return client.Python(nil), nil
	case "quarantine":
		return client.Quarantine(nil), nil
	case "quota":
		return client.Quota(nil), nil
	case "raw":
		return client.Raw(nil), nil
	case "refresh":
		return client.Refresh(nil), nil
	case "regenerate":
		return client.Regenerate(nil), nil
	case "repo":
		return client.Repo(nil), nil
	case "repository_audit_log":
		return client.RepositoryAuditLog(nil), nil
	case "repository_ecdsa_key":
		return client.RepositoryEcdsaKey(nil), nil
	case "repository_geo_ip_rule":
		return client.RepositoryGeoIpRule(nil), nil
	case "repository_geo_ip_status":
		return client.RepositoryGeoIpStatus(nil), nil
	case "repository_geo_ip_test_address":
		return client.RepositoryGeoIpTestAddress(nil), nil
	case "repository_gpg_key":
		return client.RepositoryGpgKey(nil), nil
	case "repository_privilege_input":
		return client.RepositoryPrivilegeInput(nil), nil
	case "repository_retention_rule":
		return client.RepositoryRetentionRule(nil), nil
	case "repository_rsa_key":
		return client.RepositoryRsaKey(nil), nil
	case "repository_token":
		return client.RepositoryToken(nil), nil
	case "repository_token_refresh":
		return client.RepositoryTokenRefresh(nil), nil
	case "repository_token_sync":
		return client.RepositoryTokenSync(nil), nil
	case "repository_webhook":
		return client.RepositoryWebhook(nil), nil
	case "repository_x509_ecdsa_certificate":
		return client.RepositoryX509EcdsaCertificate(nil), nil
	case "repository_x509_rsa_certificate":
		return client.RepositoryX509RsaCertificate(nil), nil
	case "reset":
		return client.Reset(nil), nil
	case "resources_rate_check":
		return client.ResourcesRateCheck(nil), nil
	case "resync":
		return client.Resync(nil), nil
	case "retention":
		return client.Retention(nil), nil
	case "rpm":
		return client.Rpm(nil), nil
	case "rsa":
		return client.Rsa(nil), nil
	case "ruby":
		return client.Ruby(nil), nil
	case "saml_group_sync":
		return client.SamlGroupSync(nil), nil
	case "scan":
		return client.Scan(nil), nil
	case "self":
		return client.Self(nil), nil
	case "service":
		return client.Service(nil), nil
	case "status":
		return client.Status(nil), nil
	case "status_basic":
		return client.StatusBasic(nil), nil
	case "storage_region":
		return client.StorageRegion(nil), nil
	case "swift":
		return client.Swift(nil), nil
	case "sync":
		return client.Sync(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "team":
		return client.Team(nil), nil
	case "terraform":
		return client.Terraform(nil), nil
	case "test":
		return client.Test(nil), nil
	case "token":
		return client.Token(nil), nil
	case "transfer_region":
		return client.TransferRegion(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_auth_token":
		return client.UserAuthToken(nil), nil
	case "user_authentication_token":
		return client.UserAuthenticationToken(nil), nil
	case "user_brief":
		return client.UserBrief(nil), nil
	case "user_profile":
		return client.UserProfile(nil), nil
	case "vagrant":
		return client.Vagrant(nil), nil
	case "validate":
		return client.Validate(nil), nil
	case "version":
		return client.Version(nil), nil
	case "vulnerability":
		return client.Vulnerability(nil), nil
	case "vulnerability_policy":
		return client.VulnerabilityPolicy(nil), nil
	case "webhook":
		return client.Webhook(nil), nil
	case "x509_ecdsa":
		return client.X509Ecdsa(nil), nil
	case "x509_rsa":
		return client.X509Rsa(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
