// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/cloudsmith-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.CloudsmithSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.CloudsmithSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.CloudsmithSDK, name string) (sdk.CloudsmithEntity, error) {
	switch strings.ToLower(name) {
	case "cargo":
		return client.Cargo(nil), nil
	case "composer":
		return client.Composer(nil), nil
	case "conda":
		return client.Conda(nil), nil
	case "cran":
		return client.Cran(nil), nil
	case "dart":
		return client.Dart(nil), nil
	case "deb":
		return client.Deb(nil), nil
	case "distribution_full":
		return client.DistributionFull(nil), nil
	case "docker":
		return client.Docker(nil), nil
	case "dynamic_mapping":
		return client.DynamicMapping(nil), nil
	case "entitlement":
		return client.Entitlement(nil), nil
	case "file":
		return client.File(nil), nil
	case "format":
		return client.Format(nil), nil
	case "gon":
		return client.Gon(nil), nil
	case "helm":
		return client.Helm(nil), nil
	case "hex":
		return client.Hex(nil), nil
	case "huggingface":
		return client.Huggingface(nil), nil
	case "maven":
		return client.Maven(nil), nil
	case "namespace":
		return client.Namespace(nil), nil
	case "namespace_audit_log":
		return client.NamespaceAuditLog(nil), nil
	case "npm":
		return client.Npm(nil), nil
	case "nuget":
		return client.Nuget(nil), nil
	case "org":
		return client.Org(nil), nil
	case "organization_group_sync":
		return client.OrganizationGroupSync(nil), nil
	case "organization_group_sync_status":
		return client.OrganizationGroupSyncStatus(nil), nil
	case "organization_invite":
		return client.OrganizationInvite(nil), nil
	case "organization_invite_extend":
		return client.OrganizationInviteExtend(nil), nil
	case "organization_membership":
		return client.OrganizationMembership(nil), nil
	case "organization_membership_role_update":
		return client.OrganizationMembershipRoleUpdate(nil), nil
	case "organization_membership_visibility_update":
		return client.OrganizationMembershipVisibilityUpdate(nil), nil
	case "organization_package_license_policy":
		return client.OrganizationPackageLicensePolicy(nil), nil
	case "organization_package_vulnerability_policy":
		return client.OrganizationPackageVulnerabilityPolicy(nil), nil
	case "organization_saml_auth":
		return client.OrganizationSamlAuth(nil), nil
	case "organization_team":
		return client.OrganizationTeam(nil), nil
	case "organization_team_member":
		return client.OrganizationTeamMember(nil), nil
	case "package":
		return client.Package(nil), nil
	case "package_deny_policy":
		return client.PackageDenyPolicy(nil), nil
	case "package_file_parts_upload":
		return client.PackageFilePartsUpload(nil), nil
	case "package_file_upload":
		return client.PackageFileUpload(nil), nil
	case "package_license_policy_evaluation":
		return client.PackageLicensePolicyEvaluation(nil), nil
	case "package_version_badge":
		return client.PackageVersionBadge(nil), nil
	case "package_vulnerability_policy_evaluation":
		return client.PackageVulnerabilityPolicyEvaluation(nil), nil
	case "provider_setting":
		return client.ProviderSetting(nil), nil
	case "provider_settings_write":
		return client.ProviderSettingsWrite(nil), nil
	case "python":
		return client.Python(nil), nil
	case "quota":
		return client.Quota(nil), nil
	case "repo":
		return client.Repo(nil), nil
	case "repository_audit_log":
		return client.RepositoryAuditLog(nil), nil
	case "repository_ecdsa_key":
		return client.RepositoryEcdsaKey(nil), nil
	case "repository_geo_ip_rule":
		return client.RepositoryGeoIpRule(nil), nil
	case "repository_geo_ip_status":
		return client.RepositoryGeoIpStatus(nil), nil
	case "repository_geo_ip_test_address":
		return client.RepositoryGeoIpTestAddress(nil), nil
	case "repository_gpg_key":
		return client.RepositoryGpgKey(nil), nil
	case "repository_privilege_dict":
		return client.RepositoryPrivilegeDict(nil), nil
	case "repository_retention_rule":
		return client.RepositoryRetentionRule(nil), nil
	case "repository_rsa_key":
		return client.RepositoryRsaKey(nil), nil
	case "repository_token":
		return client.RepositoryToken(nil), nil
	case "repository_token_refresh":
		return client.RepositoryTokenRefresh(nil), nil
	case "repository_token_sync":
		return client.RepositoryTokenSync(nil), nil
	case "repository_webhook":
		return client.RepositoryWebhook(nil), nil
	case "repository_x509_ecdsa_certificate":
		return client.RepositoryX509EcdsaCertificate(nil), nil
	case "repository_x509_rsa_certificate":
		return client.RepositoryX509RsaCertificate(nil), nil
	case "resources_rate_check":
		return client.ResourcesRateCheck(nil), nil
	case "rpm":
		return client.Rpm(nil), nil
	case "ruby":
		return client.Ruby(nil), nil
	case "service":
		return client.Service(nil), nil
	case "status_basic":
		return client.StatusBasic(nil), nil
	case "storage_region":
		return client.StorageRegion(nil), nil
	case "swift":
		return client.Swift(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_auth_token":
		return client.UserAuthToken(nil), nil
	case "user_authentication_token":
		return client.UserAuthenticationToken(nil), nil
	case "user_brief":
		return client.UserBrief(nil), nil
	case "user_profile":
		return client.UserProfile(nil), nil
	case "vulnerability":
		return client.Vulnerability(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
